# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme

skin: "/assets/css/skins/default.css"
>>>>>>> upstream/master
locale: en-US
title: JPWalker
description: A Place to Share My Thoughts
baseurl: ""
url: "jpwalker625.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"

read_time: true
words_per_minute: 150
mathjax: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "A-108431256-1"
disqus:
  shortname: "databeta-org"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
# permalink: /:categories/:title/
encoding: UTF-8
markdown: kramdown
exclude: ['*.Rmd']
feed:
  path: atom.xml


paginate: 5
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  books:
    output: true
    permalink: /:collection/:path/


# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
## Collection defaults
  - scope:
      path: "_books"
      type: books
    values:
      layout: post
      comments: true
      share: true

# Site Author Use the _data authors.yml to override these settings
author:
  name: Joseph Walker
  picture:
  email: jpwalker625@gmail.com
  links: false
   # - title:
   #   url:
   #   icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Github
    url: https://github.com/jpwalker625
    icon: fab fa-github
  - title: Instagram
    url: https://instagram.com/tictacjoe
    icon: fab fa-instagram
  - title: LinkedIn
    url: https://www.linkedin.com/in/jpwalker625/
    icon: fab fa-linkedin

